# Generated by Django 6.0.6 on 2026-06-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mistakes', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mistakes', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
