# Generated by Django 6.0.6 on 2026-06-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_team_name', models.CharField(blank=True, max_length=128)),
                ('right_team_name', models.CharField(blank=True, max_length=128)),
                ('left_team_mistakes', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('right_team_mistakes', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
