# Generated by Django 6.0.6 on 2026-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_team_name', models.CharField(blank=True)),
                ('right_team_name', models.CharField(blank=True)),
                ('left_team_mistakes', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('right_team_mistakes', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='LeftTeam',
        ),
        migrations.DeleteModel(
            name='RightTeam',
        ),
    ]
