# Generated by Django 6.0.6 on 2026-06-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamsstat_delete_leftteam_delete_rightteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamsStat',
            new_name='TeamsState',
        ),
    ]
