# Generated by Django 6.0.6 on 2026-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='points',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(),
        ),
    ]
