# Generated by Django 6.0.6 on 2026-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_option_points_alter_option_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
