# Generated by Django 6.0.6 on 2026-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_option_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
