# Generated by Django 6.0.6 on 2026-06-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
