# Generated by Django 6.0.6 on 2026-06-21 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
