# Generated by Django 6.0.6 on 2026-06-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_option_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
