# Generated by Django 6.0.6 on 2026-06-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiplier',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
